[package]
name = "text-chunking"
version = "0.1.0"
edition = "2024"
description = "Slipstream Text Chunking library text chunking"
authors = ["Slipstream Team"]
repository = "https://git.wagyu.icu/slipstream/text-chunking"
homepage = "https://git.wagyu.icu/slipstream"
publish = ["forgejo"]
keywords = [
]
categories = ["development-tools::debugging", "network-programming", "web-programming"]
readme = "README.md"
license = "none"

[package.metadata.release]
sign-commit = false
tag = false
registry = "forgejo"
# Add [ci skip] to commit messages to prevent CI triggers
pre-release-commit-message = "Release {{version}} [ci skip]"

[dependencies]
eyre = "0.6"
