name: CI Build and Publish

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on:
      - ubuntu-latest
    container:
      image: casualjim/rust-builder:1.91-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install mise
        uses: jdx/mise-action@v3
        env:
          MISE_GITHUB_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
          CARGO_REGISTRIES_FORGEJO_TOKEN: "Bearer ${{ secrets.CARGO_REGISTRIES_FORGEJO_TOKEN }}"
        with:
          experimental: true
          install: true
          cache: false

      - name: Install npm dependencies
        run: bun install
        shell: bash

      - name: Run tests
        env:
          CARGO_REGISTRIES_FORGEJO_TOKEN: "Bearer ${{ secrets.CARGO_REGISTRIES_FORGEJO_TOKEN }}"
        run: |
          cargo nextest run --all-features --no-tests pass

      - name: Publish to Cargo Registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          CARGO_REGISTRIES_FORGEJO_TOKEN: "Bearer ${{ secrets.CARGO_REGISTRIES_FORGEJO_TOKEN }}"
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          cargo release patch --execute --no-confirm --all-features
